- hosts:
    - master
  gather_facts: yes  
  become: yes
  tasks: 
    - name: download etcd     
      get_url:
        url: "https://github.com/etcd-io/etcd/releases/download/v3.4.24/etcd-v3.4.24-linux-amd64.tar.gz"
        dest: /tmp
        mode: '0666'
        
    - name: Extract etcd archive
      unarchive:
        src: /tmp/etcd-v3.4.24-linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Move etcd binaries
      copy:
        src: "/tmp/etcd-v3.4.24-linux-amd64/{{ item }}"
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: '0755'
        remote_src: yes
      loop:
        - etcd
        - etcdctl

    - name: Create etcd directory
      file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      loop:
        - /etc/etcd
        - /var/lib/etcd
      
    - name: Moove certificate
      copy:
        src: "/srv/cert/{{ item }}" 
        dest: /etc/etcd/
        owner: root
        group: root
        mode: '0755'
        remote_src: yes
      loop:
        - ca.pem
        - kubernetes-key.pem
        - kubernetes.pem

    - name: Create etcd service
      template:
        src: ../template/etcd.j2
        dest: /etc/systemd/system/etcd.service
        mode: 0644
    
    - name: Reload Daemon Systemd
      systemd:
        daemon_reload: true
    
    - name: Start etcd service
      systemd:
        name: etcd
        state: started
        enabled: true



